baseURL = "https://lw19960617.github.io/"
theme = "hugo-goa"
author = "lw"
title = "Another Hugo Blog"
builddrafts = false
canonifyurls = false
languageCode = "en-US"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"


[params]
author = "lw"
intro = "Say hello to world"
description = "Description"
authorimage = "mg.jpg"
dateformat = "Jan 2, 2006"

[params.meta]
description = "Simple minimalist theme"
keywords = "minimalist,blog,goa,hugo,developer"

[params.social]
github = "<username>"
twitter = "a wall stop me"
facebook = "a wall stop me"
google = "<username>"
stackoverflow = "<username>"
email = "739215526@qq,com"

[params.extra]
copyright = "copyright @ Rajesh Shenoy"
poweredby = true
highlightjs = true

[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "/post/"
